settings:
  log-to-console: false
  min-players: 1
  prefix: "&#3399ff&lOGGiveaway &8Â» &f"

scheduler:
  interval-seconds: 0  # 0 = Disabled, 3600 = 1 Hour

animations:
  blacksmith:
    enabled: true
    chance: 50
  spiral:
    enabled: true
    chance: 50

messages:
  broadcast:
    start:
      - "&8&m                                                &r"
      - " &b&lðŸŽ‰ GIVEAWAY STARTED! ðŸŽ‰"
      - " "
      - " &fRolling the dice..."
      - " &bCheck the center of the hub!"
      - "&8&m                                                &r"
    winner:
      - "&8&m                                                &r"
      - " &b&lðŸ’Ž GIVEAWAY ENDED! ðŸ’Ž"
      - " "
      - " &fThe winner is:"
      - " &b&n%player%"
      - "&8&m                                                &r"
  bossbar:
    rolling: "&b&lâš¡ Choosing... &f%player%"
    winner: "&b&lðŸ’Ž WINNER: &f%player% &b&lðŸ’Ž"